### ISSUE TITLE
mismatch implementation of axial encoding in `self-attn/rope_self_attn.py` and `Swin-Transformer/models/swin_transformer_rope.py`

### ISSUE THREAD

**Issue by wanghaoyucn** [naver-ai/rope-vit#1]
Hello, thanks for your work. It really helps!

I found a mismatch between the function definition and calling of `compute_axial_cis` in `self-attn/rope_self_attn.py`. 

https://github.com/naver-ai/rope-vit/blob/27eb695d29526d90f7dd4cd1d243a27f4f940754/self-attn/rope_self_attn.py#L42-L52
https://github.com/naver-ai/rope-vit/blob/27eb695d29526d90f7dd4cd1d243a27f4f940754/self-attn/rope_self_attn.py#L100-L119

The arguments passed in when the function is called don't match.

It seems that these code are partly copied from the `swin_transformer_rope.py`, because it also tries to initialize the axial freqs using `init_random_2d_freqs` similar to rope mixed. 
https://github.com/naver-ai/rope-vit/blob/27eb695d29526d90f7dd4cd1d243a27f4f940754/Swin-Transformer/models/swin_transformer_rope.py#L27

The bug in `self-attn/rope_self_attn.py` is more likely some typo. However, could you please help me with the initialization of rope axial in `Swin-Transformer/models/swin_transformer_rope.py`? The implementation in code didn't use the standard way to initialize `freqs_x` and `freqs_y`.

**Comment by bhheo** [comment]
Hi [wanghaoyucn](https://github.com/wanghaoyucn)

Thank you for reporting the problem.
Sorry, I wrongly copied the code.

I fixed the problem in `self-attn/rope_self_attn.py`. 
Please check the new commit 2df6a96.

In self_attn, the axial frequencies are hardcoded in the function
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L44-L45
On the other hand, window attention in Swin uses fixed frequencies 
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/models/swin_transformer_rope.py#L27-L41
Note that these two parts make the same frequencies when `rotate=False` for `init_random_2d_freqs` in Swin.

Thank you again for your bug reports.
Please let me know if you need any further help.

**Comment by wanghaoyucn** [comment]
Thanks for your kind reply! I figured it out. I'm also curious about the choice of `theta=10.0` instead of `theta=100.0` in swin transformer setting. Is this because the token length in the window is smaller than the length in ViT?

**Comment by bhheo** [comment]
For swin, I used theta=50 for axial and theta=10 for mixed.
You can find it from swin configs.
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/Swin-Transformer/configs/swinrope/swin_rope_axial_base_patch4_window7_224.yaml#L10-L13

https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/Swin-Transformer/configs/swinrope/swin_rope_mixed_base_patch4_window7_224.yaml#L10-L13

I will revise ‘models’ code to notice it on future commits.

I choose theta=50 for swin because window size of swin 7x7 is half of vit 14x14 at 224x224 resolution.
For mixed, I put smaller theta=10 to avoid freqs initialize close to 0. But, it is not significant because they are learnable.

**Comment by wanghaoyucn** [comment]
Thanks a lot for helping!
