### ISSUE TITLE
Question Regarding Indexing in apply_rotary_emb Function

### ISSUE THREAD

**Issue by 2JONAS** [naver-ai/rope-vit#6]
Thank you for your outstanding work.

In rope-vit/self-attn/rope_self_attn.py, line 143:

q[:, :, 1:], k[:, :, 1:] = apply_rotary_emb(q[:, :, 1:], k[:, :, 1:], freqs_cis=freqs_cis)

Could you please clarify why the slicing of the last dimension starts from index 1 instead of 0? I’m curious to understand the reasoning behind this design choice.

**Comment by bhheo** [comment]
Hi

Thank you for your interest in our work

`[:, :, 1:]` for the line is used to exclude `cls_token` from rotary embedding
https://github.com/naver-ai/rope-vit/blob/c316aecc0be984dc3d23fa79c056da290be7a3ec/models/vit_rope.py#L95

Because the `cls_token` is concatenated at the start of tokens, like
https://github.com/naver-ai/rope-vit/blob/c316aecc0be984dc3d23fa79c056da290be7a3ec/models/vit_rope.py#L185
We exclude this token from the rotary embedding function.

Note that the indexing is not used for Swin, since Swin doesn't have `cls_token`
https://github.com/naver-ai/rope-vit/blob/c316aecc0be984dc3d23fa79c056da290be7a3ec/models/swin_transformer_rope.py#L120

I hope this response answers your question

**Comment by 2JONAS** [comment]
Thanks for the detailed explanation. Very helpful!
